name: Docker Image CI for GHCR

on:
  push:
    branches: [ main ]

jobs:
  build_publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Login to GHCR
    - name: Login to GHCR
      run: echo "${{ secrets.GHCR_PA_TOKEN }}" | docker login ghcr.io -u snadboy --password-stdin

    # Build and push Docker image with 'latest' and version tags
    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/snadboy/slabels:latest -t ghcr.io/snadboy/slabels:${{ github.run_number }} ..
        docker push ghcr.io/snadboy/slabels:latest
        docker push ghcr.io/snadboy/slabels:${{ github.run_number }}

    # Install GitHub CLI
    - name: Install GitHub CLI
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt install gh

    # Authenticate with GitHub CLI
    - name: Authenticate with GitHub CLI
      run: echo "${{ secrets.GHCR_PA_TOKEN }}" | gh auth login --with-token

    # Make Docker image public
    - name: Make Docker image public
      run: gh package update snadboy/slabels --public

    # Install jq for JSON processing
    - name: Install jq
      run: sudo apt-get install jq

    # Keep only last three images
    - name: Keep only last three images
      run: |
        versions=$(gh api user/packages/container/slabels/versions --paginate | jq -r '.[] | .name')
        versions_to_delete=$(echo "$versions" | sort -r | tail -n +4)
        for version in $versions_to_delete; do
          gh api -X DELETE user/packages/container/slabels/versions/$version
        done