name: Docker Image CI for GHCR

on:
  push:
    branches: [ main ]

jobs:
  build_publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Login to GHCR
    - name: Login to GHCR
      run: echo "${{ secrets.GHCR_PA_TOKEN }}" | docker login ghcr.io -u snadboy --password-stdin

    # Build and push Docker image with 'latest' and version tags
    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/snadboy/slabels:latest -t ghcr.io/snadboy/slabels:${{ github.run_number }} .
        docker push ghcr.io/snadboy/slabels:latest
        docker push ghcr.io/snadboy/slabels:${{ github.run_number }}

    # Install GitHub CLI
    - name: Install GitHub CLI
      run: |
        curl -sSL https://github.com/cli/cli/releases/download/v2.4.0/gh_2.4.0_linux_amd64.tar.gz | sudo tar xz -C /usr/local/bin --strip-components=2 gh_2.4.0_linux_amd64/bin/gh

    # Authenticate with GitHub CLI
    - name: Authenticate with GitHub CLI
      run: echo "${{ secrets.GHCR_PA_TOKEN }}" | gh auth login --with-token

    # Make Docker image public
    - name: Make Docker image public
      run: |
        package_id=$(curl -s -H "Authorization: token ${{ secrets.GHCR_PA_TOKEN }}" https://api.github.com/user/packages/container/slabels/versions | jq -r '.[0].id')
        curl -X PATCH -H "Authorization: token ${{ secrets.GHCR_PA_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/user/packages/container/slabels/versions/$package_id -d '{"visibility":"public"}'

    # Install jq for JSON processing
    - name: Install jq
      run: sudo apt-get install jq

    # Keep only last three images
    - name: Keep only last three images
      run: |
        package_versions=$(gh package version list --package-type container --repo snadboy/slabels --limit 100)
        versions_to_delete=$(echo "$package_versions" | jq -r '.[].id' | sort -r | tail -n +4)
        for version in $versions_to_delete; do
          gh package version delete --package-type container --repo snadboy/slabels --version-id $version --confirm
        done